'use client';
import {useState,useRef,useCallback,useEffect} from 'react';import {get,set,del} from 'idb-keyval';import {validateWorkspace,type Workspace,type Snapshot} from '@/lib/model';
type Cached=Snapshot&{dirty:boolean};
export type SaveStatus='loading'|'saved'|'saving'|'offline'|'error'|'conflict';
const CACHE='jotstead.workspace.v1';
export function useWorkspace(){
 const [workspace,setWorkspace]=useState<Workspace|null>(null);const [status,setStatus]=useState<SaveStatus>('loading');const [error,setError]=useState('');const [authRequired,setAuth]=useState(false);const [serverVersion,setServerVersion]=useState<Snapshot|null>(null);
 const current=useRef<Workspace|null>(null),revision=useRef(0),generation=useRef(0),savedGeneration=useRef(0),busy=useRef(false),blocked=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),pending=useRef<{data:Workspace;baseRevision:number;mutationId:string;generation:number}|null>(null),cacheChain=useRef(Promise.resolve());
 const cache=useCallback((dirty:boolean)=>{const c:Cached={data:current.current!,revision:revision.current,dirty};cacheChain.current=cacheChain.current.catch(()=>{}).then(()=>set(CACHE,c)).catch(()=>{setError('Device storage is unavailable. Keep this tab open until changes are saved, or export a copy.');});},[]);
 const flush=useCallback(async function save(){if(!current.current||busy.current||blocked.current||generation.current===savedGeneration.current)return;busy.current=true;setStatus('saving');const job=pending.current??{data:current.current,baseRevision:revision.current,mutationId:crypto.randomUUID(),generation:generation.current};pending.current=job;
 try{const r=await fetch('/api/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:job.data,baseRevision:job.baseRevision,mutationId:job.mutationId})});if(r.status===401){setAuth(true);blocked.current=true;throw new Error('Your session expired. Sign in again to save your draft.');}if(r.status===409){blocked.current=true;const latest=await fetch('/api/workspace');if(latest.ok)setServerVersion(await latest.json());setStatus('conflict');setError('This workspace changed elsewhere. Your draft is safe on this device. Export it before choosing which version to keep.');return;}const body=await r.json();if(!r.ok)throw new Error(body.error||'Could not save');if(body.revision!==job.baseRevision+1){blocked.current=true;setServerVersion(body);setStatus('conflict');setError('A retry found newer server changes. Your local draft is preserved.');return;}revision.current=body.revision;savedGeneration.current=job.generation;pending.current=null;setError('');cache(generation.current!==savedGeneration.current);setStatus('saved');
 }catch(e){setStatus(navigator.onLine?'error':'offline');setError(e instanceof Error?e.message:'Save failed. Your draft is stored on this device.');cache(true);}finally{busy.current=false;if(!blocked.current&&pending.current===null&&generation.current!==savedGeneration.current)timer.current=setTimeout(()=>void save(),300);}
 },[cache]);
 const load=useCallback(async()=>{setStatus('loading');setAuth(false);blocked.current=false;const cached=await get<Cached>(CACHE).catch(()=>undefined);
 try{const r=await fetch('/api/workspace',{cache:'no-store'});if(r.status===401){setAuth(true);if(cached?.dirty){current.current=cached.data;setWorkspace(cached.data);revision.current=cached.revision;generation.current=1;blocked.current=true;}setStatus('error');return;}if(!r.ok)throw new Error('Could not load workspace');const s:Snapshot=await r.json();validateWorkspace(s.data);revision.current=s.revision;
 if(cached?.dirty){validateWorkspace(cached.data);current.current=cached.data;setWorkspace(cached.data);generation.current=1;savedGeneration.current=0;if(cached.revision!==s.revision){blocked.current=true;setServerVersion(s);setStatus('conflict');setError('A recovered draft differs from the server. Both versions are available.');return;}setStatus('saving');timer.current=setTimeout(()=>void flush(),50);}else{current.current=s.data;setWorkspace(s.data);generation.current=0;savedGeneration.current=0;cache(false);setStatus('saved');}
 }catch(e){if(cached){current.current=validateWorkspace(cached.data);revision.current=cached.revision;setWorkspace(current.current);generation.current=cached.dirty?1:0;savedGeneration.current=0;setStatus('offline');setError('Working from this device’s copy. Changes will save when your server is available.');}else{setStatus('error');setError(e instanceof Error?e.message:'Could not connect');}}
 },[cache,flush]);
 useEffect(()=>{void load();return()=>{if(timer.current)clearTimeout(timer.current);};},[load]);
 useEffect(()=>{const online=()=>{if(!blocked.current)void flush();};const offline=()=>setStatus('offline');const unload=(e:BeforeUnloadEvent)=>{if(generation.current!==savedGeneration.current){cache(true);e.preventDefault();}};const retry=setInterval(()=>{if(!blocked.current&&generation.current!==savedGeneration.current&&navigator.onLine)void flush();},15000);window.addEventListener('online',online);window.addEventListener('offline',offline);window.addEventListener('beforeunload',unload);return()=>{clearInterval(retry);window.removeEventListener('online',online);window.removeEventListener('offline',offline);window.removeEventListener('beforeunload',unload);};},[cache,flush]);
 const update=useCallback((mutate:(w:Workspace)=>void)=>{if(!current.current)return;const next=structuredClone(current.current);mutate(next);current.current=next;generation.current++;setWorkspace(next);cache(true);if(!blocked.current){setStatus(navigator.onLine?'saving':'offline');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),700);}},[cache,flush]);
 const resolveConflict=useCallback((keepDraft:boolean)=>{if(!serverVersion)return;pending.current=null;revision.current=serverVersion.revision;blocked.current=false;setServerVersion(null);setError('');if(keepDraft){generation.current++;savedGeneration.current=0;cache(true);void flush();}else{current.current=serverVersion.data;setWorkspace(serverVersion.data);generation.current=0;savedGeneration.current=0;cache(false);setStatus('saved');}},[serverVersion,cache,flush]);
 const signOut=useCallback(async()=>{if(generation.current!==savedGeneration.current)throw new Error('Save or export your draft before signing out.');await fetch('/api/auth',{method:'DELETE'});await del(CACHE);current.current=null;setWorkspace(null);setAuth(true);setStatus('loading');},[]);
 return {workspace,update,status,error,authRequired,load,flush,resolveConflict,serverVersion,signOut};
}
