'use client';
import {useEffect,useRef,useState,useMemo,useCallback} from 'react';
import {useEditor,EditorContent,type Editor} from '@tiptap/react';import {BubbleMenu} from '@tiptap/react/menus';import StarterKit from '@tiptap/starter-kit';import Placeholder from '@tiptap/extension-placeholder';import TaskList from '@tiptap/extension-task-list';import TaskItem from '@tiptap/extension-task-item';import Image from '@tiptap/extension-image';import {TableKit} from '@tiptap/extension-table';import {Details,DetailsSummary,DetailsContent} from '@tiptap/extension-details';import {TextStyle,Color} from '@tiptap/extension-text-style';import Highlight from '@tiptap/extension-highlight';import UniqueID from '@tiptap/extension-unique-id';import {Markdown} from '@tiptap/markdown';
import {TextTIcon,TextHOneIcon,TextHTwoIcon,TextHThreeIcon,ListBulletsIcon,ListNumbersIcon,CheckSquareIcon,CaretRightIcon,QuotesIcon,CodeIcon,ImageIcon,PaperclipIcon,TableIcon,MinusIcon,InfoIcon,ColumnsIcon,PlusIcon,DotsSixVerticalIcon,ArrowUpIcon,ArrowDownIcon,CopyIcon,TrashIcon,TextBIcon,TextItalicIcon,TextUnderlineIcon,TextStrikethroughIcon,LinkIcon,HighlighterIcon,ArrowCounterClockwiseIcon,ArrowClockwiseIcon} from '@phosphor-icons/react';
import {Callout,Columns,Column,FileNode,PageLink} from './extensions';import {IconButton,Modal,Field} from '@/components/ui';import {safeUrl,type Doc} from '@/lib/model';
export const editorExtensions=()=>[StarterKit.configure({link:{openOnClick:false,autolink:true,defaultProtocol:'https',isAllowedUri:url=>safeUrl(url)}}),Placeholder.configure({placeholder:'Press "/" for commands…'}),TaskList,TaskItem.configure({nested:true}),Image.configure({allowBase64:false}),TableKit.configure({table:{resizable:true}}),Details.configure({persist:true,renderToggleButton:({element,isOpen})=>{element.setAttribute('aria-label',isOpen?'Collapse toggle':'Expand toggle');}}),DetailsSummary,DetailsContent,TextStyle,Color,Highlight.configure({multicolor:true}),Callout,Columns,Column,FileNode,PageLink,UniqueID.configure({types:['paragraph','heading','blockquote','codeBlock','taskItem','listItem','image','details','callout','columns','file','pageLink','table']}),Markdown];
type Command={name:string;description:string;icon:typeof TextTIcon;run:(e:Editor)=>void;keywords?:string};
export function PageEditor({content,onChange,onReady,readOnly=false,onNavigate}:{content:Doc;onChange?:(d:Doc)=>void;onReady?:(e:Editor)=>void;readOnly?:boolean;onNavigate?:(id:string)=>void}){
 const change=useRef(onChange);change.current=onChange;const [slash,setSlash]=useState<{query:string;from:number;to:number;x:number;y:number}|null>(null);const [chosen,setChosen]=useState(0);const [block,setBlock]=useState<{index:number;y:number}|null>(null);const [blockMenu,setBlockMenu]=useState(false);const [linkModal,setLinkModal]=useState(false),[link,setLink]=useState('');const [fileError,setFileError]=useState('');const fileRef=useRef<HTMLInputElement>(null),imageOnly=useRef(false),root=useRef<HTMLDivElement>(null),slashRef=useRef(slash),chosenRef=useRef(chosen);slashRef.current=slash;chosenRef.current=chosen;
 const commandsRef=useRef<Command[]>([]);const selectRef=useRef<(cmd:Command)=>void>(()=>{});
 // Hook API intentionally keeps one editor instance in this component; SSR rendering is disabled.
 const editor=useEditor({extensions:useMemo(editorExtensions,[]),content,editable:!readOnly,immediatelyRender:false,shouldRerenderOnTransaction:false,editorProps:{attributes:{class:'tiptap',role:'textbox','aria-label':'Page content','aria-multiline':'true'},handleKeyDown(_view,event){if(slashRef.current){if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();setChosen(i=>(i+(event.key==='ArrowDown'?1:-1)+commandsRef.current.length)%Math.max(commandsRef.current.length,1));return true;}if(event.key==='Enter'&&commandsRef.current[chosenRef.current]){event.preventDefault();selectRef.current(commandsRef.current[chosenRef.current]);return true;}if(event.key==='Escape'){setSlash(null);return true;}}return false;},handleClick(_view,_pos,event){const a=(event.target as HTMLElement)?.closest('[data-page-link] a');if(a&&onNavigate){event.preventDefault();const pageId=new URL((a as HTMLAnchorElement).href).searchParams.get('page');if(pageId)onNavigate(pageId);return true;}return false;},handleDrop(view,event){const index=event.dataTransfer?.getData('application/x-jotstead-block');if(!index)return false;const target=view.posAtCoords({left:event.clientX,top:event.clientY});if(!target)return false;let dst=0;view.state.doc.forEach((n,pos,i)=>{if(pos<=target.pos)dst=i;});const src=Number(index);if(src!==dst){const nodes:typeof view.state.doc[]=[];view.state.doc.forEach(n=>nodes.push(n));const [n]=nodes.splice(src,1);nodes.splice(dst,0,n);view.dispatch(view.state.tr.replaceWith(0,view.state.doc.content.size,nodes));}event.preventDefault();return true;}},onUpdate({editor:e}){change.current?.(e.getJSON() as Doc);},onTransaction({editor:e}){if(readOnly)return;const {from,empty,$from}=e.state.selection;const before=$from.parent.textBetween(0,$from.parentOffset,'\0');const match=before.match(/(?:^|\s)\/([a-zA-Z0-9 -]*)$/);if(empty&&match){const coords=e.view.coordsAtPos(from);const next={query:match[1],from:from-match[1].length-1,to:from,x:Math.min(coords.left,window.innerWidth-300),y:Math.min(coords.bottom+6,window.innerHeight-350)};if(slashRef.current?.query!==next.query)setChosen(0);setSlash(prev=>prev&&JSON.stringify(prev)===JSON.stringify(next)?prev:next);}else setSlash(null);}});
 useEffect(()=>{if(editor){onReady?.(editor);}},[editor,onReady]);
 useEffect(()=>{if(editor&&JSON.stringify(editor.getJSON())!==JSON.stringify(content)){editor.commands.setContent(content,{emitUpdate:false});}},[content,editor]);
 const commands=useMemo<Command[]>(()=>[
 {name:'Text',description:'Just start writing with plain text.',icon:TextTIcon,run:e=>e.chain().focus().setParagraph().run()},
 {name:'Heading 1',description:'Big section heading.',icon:TextHOneIcon,keywords:'h1',run:e=>e.chain().focus().toggleHeading({level:1}).run()},
 {name:'Heading 2',description:'Medium section heading.',icon:TextHTwoIcon,keywords:'h2',run:e=>e.chain().focus().toggleHeading({level:2}).run()},
 {name:'Heading 3',description:'Small section heading.',icon:TextHThreeIcon,keywords:'h3',run:e=>e.chain().focus().toggleHeading({level:3}).run()},
 {name:'To-do list',description:'Track tasks with a checklist.',icon:CheckSquareIcon,keywords:'todo task check',run:e=>e.chain().focus().toggleTaskList().run()},
 {name:'Bulleted list',description:'Create a simple bulleted list.',icon:ListBulletsIcon,run:e=>e.chain().focus().toggleBulletList().run()},
 {name:'Numbered list',description:'Create a list with numbering.',icon:ListNumbersIcon,run:e=>e.chain().focus().toggleOrderedList().run()},
 {name:'Toggle list',description:'Hide and reveal nested content.',icon:CaretRightIcon,run:e=>e.chain().focus().insertContent({type:'details',attrs:{open:true},content:[{type:'detailsSummary',content:[{type:'text',text:'Toggle'}]},{type:'detailsContent',content:[{type:'paragraph'}]}]}).run()},
 {name:'Callout',description:'Make something stand out.',icon:InfoIcon,run:e=>e.chain().focus().insertContent({type:'callout',content:[{type:'paragraph',content:[{type:'text',text:'Something worth remembering.'}]}]}).run()},
 {name:'Quote',description:'Capture a quote.',icon:QuotesIcon,run:e=>e.chain().focus().toggleBlockquote().run()},
 {name:'Divider',description:'Visually divide blocks.',icon:MinusIcon,run:e=>e.chain().focus().setHorizontalRule().run()},
 {name:'Code',description:'A block of code.',icon:CodeIcon,run:e=>e.chain().focus().toggleCodeBlock().run()},
 {name:'Image',description:'Upload an image.',icon:ImageIcon,run:()=>{imageOnly.current=true;fileRef.current?.click();}},
 {name:'File',description:'Upload an attachment.',icon:PaperclipIcon,run:()=>{imageOnly.current=false;fileRef.current?.click();}},
 {name:'Table',description:'A simple table.',icon:TableIcon,run:e=>e.chain().focus().insertTable({rows:3,cols:3,withHeaderRow:true}).run()},
 {name:'Columns',description:'Two columns side by side.',icon:ColumnsIcon,run:e=>e.chain().focus().insertContent({type:'columns',content:[{type:'column',content:[{type:'paragraph',content:[{type:'text',text:'Left column'}]}]},{type:'column',content:[{type:'paragraph',content:[{type:'text',text:'Right column'}]}]}]}).run()}
 ],[]);
 const filtered=commands.filter(c=>`${c.name} ${c.keywords||''}`.toLowerCase().includes(slash?.query.toLowerCase()||''));commandsRef.current=filtered;
 const select=useCallback((cmd:Command)=>{if(!editor)return;const s=slashRef.current;if(s)editor.chain().focus().deleteRange({from:s.from,to:s.to}).run();setSlash(null);cmd.run(editor);},[editor]);selectRef.current=select;
 function mutateBlock(action:'up'|'down'|'duplicate'|'delete'){if(!editor||!block)return;const nodes:typeof editor.state.doc[]=[];editor.state.doc.forEach(n=>nodes.push(n));const i=block.index;if(action==='delete')nodes.splice(i,1);if(action==='duplicate')nodes.splice(i+1,0,nodes[i]);if(action==='up'&&i>0)[nodes[i-1],nodes[i]]=[nodes[i],nodes[i-1]];if(action==='down'&&i<nodes.length-1)[nodes[i+1],nodes[i]]=[nodes[i],nodes[i+1]];if(!nodes.length)nodes.push(editor.schema.nodes.paragraph.create());editor.view.dispatch(editor.state.tr.replaceWith(0,editor.state.doc.content.size,nodes));setBlockMenu(false);setBlock(null);}
 if(!editor)return <div className="editor-loading"/>;
 const format=(label:string,icon:typeof TextBIcon,active:string,run:()=>void)=><IconButton key={label} label={label} aria-pressed={editor.isActive(active)} onMouseDown={e=>e.preventDefault()} onClick={run}>{(() =>{const Icon=icon;return <Icon size={17}/>;})()}</IconButton>;
 return <div ref={root} className={`editor-root ${readOnly?'readonly':''}`} onMouseMove={e=>{if(readOnly||blockMenu)return;const el=(e.target as HTMLElement).closest('.tiptap > *');if(el&&el.parentElement?.classList.contains('tiptap')){const i=Array.from(el.parentElement.children).indexOf(el);setBlock({index:i,y:el.getBoundingClientRect().top-root.current!.getBoundingClientRect().top});}}} onMouseLeave={()=>{if(!blockMenu)setBlock(null);}}>
 <EditorContent editor={editor}/>
 {!readOnly&&<><input ref={fileRef} type="file" aria-label="Upload attachment" className="hidden" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>20*1024*1024)throw new Error('Files can be up to 20 MB.');const form=new FormData();form.set('file',file);const r=await fetch('/api/uploads',{method:'POST',body:form});const b=await r.json();if(!r.ok)throw new Error(b.error);if(imageOnly.current&&!b.image)throw new Error('Choose a PNG, JPEG, WebP, or GIF image.');if(b.image)editor.chain().focus().setImage({src:b.url,alt:file.name}).run();else editor.chain().focus().insertContent({type:'file',attrs:{src:b.url,name:file.name,size:file.size}}).run();setFileError('');}catch(err){setFileError(err instanceof Error?err.message:'Upload failed');}e.target.value='';}}/>
 <BubbleMenu editor={editor} className="format-menu" options={{placement:'top',offset:8}}>{format('Bold',TextBIcon,'bold',()=>editor.chain().focus().toggleBold().run())}{format('Italic',TextItalicIcon,'italic',()=>editor.chain().focus().toggleItalic().run())}{format('Underline',TextUnderlineIcon,'underline',()=>editor.chain().focus().toggleUnderline().run())}{format('Strike',TextStrikethroughIcon,'strike',()=>editor.chain().focus().toggleStrike().run())}{format('Code',CodeIcon,'code',()=>editor.chain().focus().toggleCode().run())}{format('Highlight',HighlighterIcon,'highlight',()=>editor.chain().focus().toggleHighlight().run())}<IconButton label="Add link" onMouseDown={e=>e.preventDefault()} onClick={()=>{setLink(editor.getAttributes('link').href||'');setLinkModal(true);}}><LinkIcon size={17}/></IconButton><input aria-label="Text color" type="color" defaultValue="#37352f" onChange={e=>editor.chain().focus().setColor(e.target.value).run()}/></BubbleMenu>
 {block&&<div className="block-controls" style={{top:block.y}}><IconButton label="Insert block" onClick={()=>{let pos=0;editor.state.doc.forEach((n,_p,i)=>{if(i<=block.index)pos+=n.nodeSize;});editor.chain().focus().insertContentAt(pos,{type:'paragraph',content:[{type:'text',text:'/'}]}).setTextSelection(pos+2).run();}}><PlusIcon size={17}/></IconButton><button className="icon-button block-handle" aria-label="Block actions" draggable onDragStart={e=>e.dataTransfer.setData('application/x-jotstead-block',String(block.index))} onClick={()=>setBlockMenu(v=>!v)}><DotsSixVerticalIcon size={17}/></button>{blockMenu&&<div className="menu block-menu"><button onClick={()=>mutateBlock('up')}><ArrowUpIcon size={16}/>Move up</button><button onClick={()=>mutateBlock('down')}><ArrowDownIcon size={16}/>Move down</button><button onClick={()=>mutateBlock('duplicate')}><CopyIcon size={16}/>Duplicate</button><button className="danger" onClick={()=>mutateBlock('delete')}><TrashIcon size={16}/>Delete</button><div className="menu-label">Turn into</div>{commands.slice(0,10).map(c=><button key={c.name} onClick={()=>{let pos=0;editor.state.doc.forEach((n,_p,i)=>{if(i<block.index)pos+=n.nodeSize;});editor.chain().focus().setTextSelection(pos+1).run();c.run(editor);setBlockMenu(false);}}><c.icon size={16}/>{c.name}</button>)}</div>}</div>}
 {slash&&<div className="slash-menu menu" role="listbox" aria-label="Block commands" style={{left:Math.max(8,slash.x),top:Math.max(48,slash.y)}}><div className="menu-label">Basic blocks</div>{filtered.length?filtered.map((c,i)=><button key={c.name} role="option" aria-selected={chosen===i} className={chosen===i?'selected':''} onMouseDown={e=>e.preventDefault()} onClick={()=>select(c)}><span className="command-icon"><c.icon size={24}/></span><span><strong>{c.name}</strong><small>{c.description}</small></span></button>):<div className="menu-label">No matching blocks</div>}</div>}
 <div className="mobile-editor-toolbar"><IconButton label="Add block" onClick={()=>{const pos=editor.state.selection.from;editor.chain().focus().insertContent('/').run();const coords=editor.view.coordsAtPos(pos);setSlash({query:'',from:pos,to:pos+1,x:12,y:Math.max(80,window.innerHeight-370)});}}><PlusIcon size={20}/></IconButton>{format('Bold',TextBIcon,'bold',()=>editor.chain().focus().toggleBold().run())}{format('Italic',TextItalicIcon,'italic',()=>editor.chain().focus().toggleItalic().run())}<IconButton label="Undo" onClick={()=>editor.chain().focus().undo().run()}><ArrowCounterClockwiseIcon size={18}/></IconButton><IconButton label="Redo" onClick={()=>editor.chain().focus().redo().run()}><ArrowClockwiseIcon size={18}/></IconButton></div>
 {fileError&&<p role="alert" className="error-text">{fileError}</p>}
 {linkModal&&<Modal title="Add a link" onClose={()=>setLinkModal(false)}><form onSubmit={e=>{e.preventDefault();if(!link)editor.chain().focus().unsetLink().run();else if(safeUrl(link))editor.chain().focus().setLink({href:link}).run();else return;setLinkModal(false);}}><Field label="Link URL"><input autoFocus value={link} onChange={e=>setLink(e.target.value)} placeholder="https://example.com"/></Field><button className="primary">Save link</button></form></Modal>}
 </>}
 </div>;
}
