'use client';
import {useEffect,useRef,type ReactNode,type ButtonHTMLAttributes} from 'react';
import {XIcon,FileTextIcon,DatabaseIcon} from '@phosphor-icons/react';
export function IconButton({label,children,...props}:ButtonHTMLAttributes<HTMLButtonElement>&{label:string}){return <button {...props} className={`icon-button ${props.className||''}`} title={label} aria-label={label}>{children}</button>;}
export function PageIcon({icon,kind='page',size=18}:{icon:string;kind?:'page'|'database';size?:number}){return icon?<span className="page-emoji" style={{fontSize:size}} aria-hidden="true">{icon}</span>:kind==='database'?<DatabaseIcon size={size} color="var(--muted)"/>:<FileTextIcon size={size} color="var(--muted)"/>;}
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();const current=ref.current;return()=>{current?.close();};},[]);return <dialog ref={ref} aria-label={title} className={`modal ${wide?'wide':''}`} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-header"><h2>{title}</h2><IconButton label="Close" onClick={onClose}><XIcon size={19}/></IconButton></div>{children}</dialog>;}
export function Menu({children,onClose,className=''}:{children:ReactNode;onClose:()=>void;className?:string}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};const click=(e:MouseEvent)=>{if(!ref.current?.contains(e.target as Node))onClose();};document.addEventListener('keydown',close);document.addEventListener('mousedown',click);return()=>{document.removeEventListener('keydown',close);document.removeEventListener('mousedown',click);};},[onClose]);return <div ref={ref} className={`menu ${className}`}>{children}</div>;}
export function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
export function EmptyState({title,description,children}:{title:string;description?:string;children?:ReactNode}){return <div className="empty-state"><FileTextIcon size={32} color="var(--muted)"/><h3>{title}</h3>{description&&<p>{description}</p>}{children}</div>;}
export function download(name:string,value:string,mime='application/json'){const url=URL.createObjectURL(new Blob([value],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
